# Generated by Django 4.2.5 on 2024-03-18 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="public",
            name="history",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="用户病史"
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="description",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="数据集描述"
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="model",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="数据集关联模型"
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="数据集名称"
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="ownerID",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="数据集所有者"
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="ownerName",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="数据集所有者姓名"
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="scene",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="数据集应用场景"
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="size",
            field=models.FloatField(blank=True, null=True, verbose_name="数据集大小"),
        ),
        migrations.AlterField(
            model_name="data",
            name="time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="数据集上传时间"),
        ),
        migrations.AlterField(
            model_name="diagnosismission",
            name="data",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="任务数据集"
            ),
        ),
        migrations.AlterField(
            model_name="diagnosismission",
            name="description",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="任务描述"
            ),
        ),
        migrations.AlterField(
            model_name="diagnosismission",
            name="endTime",
            field=models.DateField(blank=True, null=True, verbose_name="任务结束时间"),
        ),
        migrations.AlterField(
            model_name="diagnosismission",
            name="model",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="任务模型"
            ),
        ),
        migrations.AlterField(
            model_name="diagnosismission",
            name="researcherEstablish",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="是否为科研人员创建"
            ),
        ),
        migrations.AlterField(
            model_name="diagnosismission",
            name="resultDisease",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="任务结果"
            ),
        ),
        migrations.AlterField(
            model_name="diagnosismission",
            name="resultStage",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="任务应用场景"
            ),
        ),
        migrations.AlterField(
            model_name="diagnosismission",
            name="scene",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="任务应用场景"
            ),
        ),
        migrations.AlterField(
            model_name="diagnosismission",
            name="startTime",
            field=models.DateField(blank=True, null=True, verbose_name="任务开始时间"),
        ),
        migrations.AlterField(
            model_name="diagnosismission",
            name="state",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="任务状态"
            ),
        ),
        migrations.AlterField(
            model_name="diagnosismission",
            name="whetherPublic",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="是否通知病人"
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="department",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="所属部门"
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="hospital",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="所属医院"
            ),
        ),
        migrations.AlterField(
            model_name="model",
            name="data",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="模型数据集"
            ),
        ),
        migrations.AlterField(
            model_name="model",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="模型描述"),
        ),
        migrations.AlterField(
            model_name="model",
            name="name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="模型名称"
            ),
        ),
        migrations.AlterField(
            model_name="model",
            name="ownerID",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="模型所有者"
            ),
        ),
        migrations.AlterField(
            model_name="model",
            name="ownerName",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="模型所有者姓名"
            ),
        ),
        migrations.AlterField(
            model_name="model",
            name="scene",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="模型应用场景"
            ),
        ),
        migrations.AlterField(
            model_name="model",
            name="time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="模型上传时间"),
        ),
        migrations.AlterField(
            model_name="model",
            name="type",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="模型类型"
            ),
        ),
        migrations.AlterField(
            model_name="planrecommendmission",
            name="data",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="任务数据集"
            ),
        ),
        migrations.AlterField(
            model_name="planrecommendmission",
            name="endTime",
            field=models.DateField(blank=True, null=True, verbose_name="任务结束时间"),
        ),
        migrations.AlterField(
            model_name="planrecommendmission",
            name="model",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="任务模型"
            ),
        ),
        migrations.AlterField(
            model_name="planrecommendmission",
            name="patient_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="backend.public",
            ),
        ),
        migrations.AlterField(
            model_name="planrecommendmission",
            name="researcherEstablish",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="是否为科研人员创建"
            ),
        ),
        migrations.AlterField(
            model_name="planrecommendmission",
            name="scene",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="任务应用场景"
            ),
        ),
        migrations.AlterField(
            model_name="planrecommendmission",
            name="startTime",
            field=models.DateField(blank=True, null=True, verbose_name="任务开始时间"),
        ),
        migrations.AlterField(
            model_name="planrecommendmission",
            name="state",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="任务状态"
            ),
        ),
        migrations.AlterField(
            model_name="planrecommendmission",
            name="whetherPublic",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="是否通知病人"
            ),
        ),
        migrations.AlterField(
            model_name="predictmission",
            name="data",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="任务数据集"
            ),
        ),
        migrations.AlterField(
            model_name="predictmission",
            name="description",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="任务描述"
            ),
        ),
        migrations.AlterField(
            model_name="predictmission",
            name="endTime",
            field=models.DateField(blank=True, null=True, verbose_name="任务结束时间"),
        ),
        migrations.AlterField(
            model_name="predictmission",
            name="model",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="任务模型"
            ),
        ),
        migrations.AlterField(
            model_name="predictmission",
            name="patient_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="backend.public",
            ),
        ),
        migrations.AlterField(
            model_name="predictmission",
            name="patient_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="患者姓名"
            ),
        ),
        migrations.AlterField(
            model_name="predictmission",
            name="researcherEstablish",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="是否为科研人员创建"
            ),
        ),
        migrations.AlterField(
            model_name="predictmission",
            name="risk",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="风险预测"
            ),
        ),
        migrations.AlterField(
            model_name="predictmission",
            name="scene",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="任务应用场景"
            ),
        ),
        migrations.AlterField(
            model_name="predictmission",
            name="startTime",
            field=models.DateField(blank=True, null=True, verbose_name="任务开始时间"),
        ),
        migrations.AlterField(
            model_name="predictmission",
            name="state",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="任务状态"
            ),
        ),
        migrations.AlterField(
            model_name="predictmission",
            name="whetherPublic",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="是否通知病人"
            ),
        ),
        migrations.AlterField(
            model_name="public",
            name="ADAS_Cog",
            field=models.FloatField(blank=True, null=True, verbose_name="ADAS_Cog"),
        ),
        migrations.AlterField(
            model_name="public",
            name="ApoE",
            field=models.FloatField(blank=True, null=True, verbose_name="ApoE"),
        ),
        migrations.AlterField(
            model_name="public",
            name="CDR_Global",
            field=models.FloatField(blank=True, null=True, verbose_name="CDR_Global"),
        ),
        migrations.AlterField(
            model_name="public",
            name="CDR_SOB",
            field=models.FloatField(blank=True, null=True, verbose_name="CDR_SOB"),
        ),
        migrations.AlterField(
            model_name="public",
            name="MMSE",
            field=models.FloatField(blank=True, null=True, verbose_name="MMSE"),
        ),
        migrations.AlterField(
            model_name="public",
            name="MRI",
            field=models.FloatField(blank=True, null=True, verbose_name="MRI"),
        ),
        migrations.AlterField(
            model_name="public",
            name="PET",
            field=models.FloatField(blank=True, null=True, verbose_name="PET"),
        ),
        migrations.AlterField(
            model_name="public",
            name="age",
            field=models.IntegerField(blank=True, null=True, verbose_name="用户年龄"),
        ),
        migrations.AlterField(
            model_name="public",
            name="birthdate",
            field=models.DateField(blank=True, null=True, verbose_name="用户生日"),
        ),
        migrations.AlterField(
            model_name="public",
            name="education",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="用户学历"
            ),
        ),
        migrations.AlterField(
            model_name="public",
            name="gender",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="用户性别"
            ),
        ),
        migrations.AlterField(
            model_name="public",
            name="identy",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="用户电话"
            ),
        ),
        migrations.AlterField(
            model_name="public",
            name="name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="用户姓名"
            ),
        ),
        migrations.AlterField(
            model_name="public",
            name="password",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="用户密码"
            ),
        ),
        migrations.AlterField(
            model_name="public",
            name="phone",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="用户电话"
            ),
        ),
        migrations.AlterField(
            model_name="public",
            name="region",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="用户住址"
            ),
        ),
        migrations.AlterField(
            model_name="researcher",
            name="department",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="所属单位"
            ),
        ),
    ]
