# Generated by Django 4.2.5 on 2024-03-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_public_history_alter_data_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="public",
            name="ADAS_Cog",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="ADAS_Cog"
            ),
        ),
        migrations.AlterField(
            model_name="public",
            name="ApoE",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="ApoE"
            ),
        ),
        migrations.AlterField(
            model_name="public",
            name="CDR_Global",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="CDR_Global"
            ),
        ),
        migrations.AlterField(
            model_name="public",
            name="CDR_SOB",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="CDR_SOB"
            ),
        ),
        migrations.AlterField(
            model_name="public",
            name="MMSE",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="MMSE"
            ),
        ),
        migrations.AlterField(
            model_name="public",
            name="MRI",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="MRI"
            ),
        ),
        migrations.AlterField(
            model_name="public",
            name="PET",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="PET"
            ),
        ),
        migrations.AlterField(
            model_name="public",
            name="age",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="用户年龄"
            ),
        ),
        migrations.AlterField(
            model_name="public",
            name="birthdate",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="用户生日"
            ),
        ),
    ]
