# Generated by Django 4.2.5 on 2024-03-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0003_alter_public_adas_cog_alter_public_apoe_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="size",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="数据集大小"
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="time",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="数据集上传时间"
            ),
        ),
        migrations.AlterField(
            model_name="public",
            name="identy",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="身份证号"
            ),
        ),
    ]
