# Generated by Django 4.2.5 on 2024-03-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0004_alter_data_size_alter_data_time_alter_public_identy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diagnosismission",
            name="endTime",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="任务结束时间"
            ),
        ),
        migrations.AlterField(
            model_name="diagnosismission",
            name="startTime",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="任务开始时间"
            ),
        ),
        migrations.AlterField(
            model_name="planrecommendmission",
            name="endTime",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="任务结束时间"
            ),
        ),
        migrations.AlterField(
            model_name="planrecommendmission",
            name="startTime",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="任务开始时间"
            ),
        ),
        migrations.AlterField(
            model_name="predictmission",
            name="endTime",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="任务结束时间"
            ),
        ),
        migrations.AlterField(
            model_name="predictmission",
            name="startTime",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="任务开始时间"
            ),
        ),
    ]
