# Generated by Django 4.2.5 on 2024-03-19 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0005_alter_diagnosismission_endtime_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="planrecommendmission",
            name="description",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="任务描述"
            ),
        ),
    ]
