# Generated by Django 4.2.5 on 2024-03-19 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0006_planrecommendmission_description"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Model",
            new_name="BigModel",
        ),
    ]
