# Generated by Django 4.2.5 on 2024-03-19 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0007_rename_model_bigmodel"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="bigmodel",
            new_name="BigModel_id_b8f370_idx",
            old_name="model_id_2ffab6_idx",
        ),
        migrations.AlterModelTable(
            name="bigmodel",
            table="BigModel",
        ),
    ]
